on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test rwx_results
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: rwx-research/setup-captain@v1

      - run: captain run rwx-results-rspec
        env:
          RWX_ACCESS_TOKEN: ${{ secrets.RWX_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: |
            rwx_results:ci

      - name: Update action.yml
        run: |
          echo "yq version: $(yq --version)"
          yq '.runs.image = "docker://rwx_results:ci"' -i action.yml
          echo "Action file contents:"
          cat action.yml

      - name: Run action
        uses: ./ # Uses an action in the root directory
        if: ${{ !cancelled() }}
        id: rwx_results
        with:
          rwx-access-token: ${{ secrets.RWX_ACCESS_TOKEN }}
          captain-test-suite-id: rwx-results-rspec
          # captain-branch-name: captain-summary
          # captain-commit-sha: 59488939c9c61646c39813adc4fb1940462de4fb
          # captain-repository: detaso/kairos
